version: '2'
services:
    fmxtocontenido-app:
        image: fmxtocontenido
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://fmxtocontenido-mariadb:3306/fmxtocontenido
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=fmxtocontenido-elasticsearch:9300
        ports:
            - 7070:7070
    fmxtocontenido-mariadb:
        extends:
            file: mariadb.yml
            service: fmxtocontenido-mariadb
    fmxtocontenido-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: fmxtocontenido-elasticsearch
